<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NaYeL" name="org.example.Runner.Runner" tests="22" failures="1" timestamp="2022-06-16T14:07:36 EET" time="1032.763" errors="1">
  <testcase name="runScenario" time="42.861" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="43.795" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="34.919" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="28.377" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="51.960" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="58.840" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="68.040" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="43.618" classname="org.example.Runner.Runner">
    <failure type="java.lang.AssertionError" message="Error in product link expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error in product link expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.example.StepDefinition.D11_SliderStepDef.navigated_slider_product_one(D11_SliderStepDef.java:22)
at ✽.should navigated to the slider_product_one page(file:///C:/Users/Mohamed/IdeaProjects/demoNopcommerceProject/src/main/resources/features/F11_Slider.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="97.992" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="37.552" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="34.238" classname="org.example.Runner.Runner">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at org.example.StepDefinition.D12_FollowUsStepDef.click_rss(D12_FollowUsStepDef.java:54)
at ✽.user click on rss(file:///C:/Users/Mohamed/IdeaProjects/demoNopcommerceProject/src/main/resources/features/F12_FollowUs.feature:20)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="33.052" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="48.166" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="23.236" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="37.542" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="66.581" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="54.829" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="35.053" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="45.284" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="36.273" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="56.132" classname="org.example.Runner.Runner"/>
  <system-out/>
  <testcase name="runScenario" time="54.423" classname="org.example.Runner.Runner"/>
  <system-out/>
</testsuite> <!-- org.example.Runner.Runner -->
